### ISSUE TITLE
Per-player journal

### ISSUE THREAD

**Issue by zeuner** [HybridDog/we_undo#1]
I think it would be useful to be able to undo/redo the last changes done by a specific player, without taking into account what other players edited.

**Comment by HybridDog** [comment]
A player should already have their own journal: https://github.com/HybridDog/we_undo/blob/master/init.lua#L167 (I'm not sure if I tested it.)
Do you mean undoing something by another player than yourself?

**Comment by zeuner** [comment]
@HybridDog: Yes, I think it would be useful to have the per-player
journals accessible by other (privileged) players.

original message follows:

**Comment by HybridDog** [comment]
Sorry for the late response.
I think instead of adding a command to we_undo to do this, another chatcommand should be added which does what you need: the `run_as` command.
You can then write e.g. `/run_as ArpiLo //show_journal` in chat to execute the /show_journal chatcommand as if you were the player named ArpiLo, the chat messages are captured and shown to you instead of that player.
(The `/` is added to the chatcommand like when invoking it oneself because it serves as neat delimiter between playername (run_as options) and the command which should be executed.)
The run_as command of course requires the server privilege.

There's a mod for extra chatcommands: https://github.com/red-001/more_chatcommands/blob/master/init.lua
The command can be added there, how do you think about it?

**Comment by HybridDog** [comment]
@zeuner, I've implemented run_as: https://github.com/HybridDog/more_chatcommands/tree/run_as
